package com.lending.platform.entity;

public enum DocumentType {
    BUSINESS_TAX_RETURN,
    PERSONAL_TAX_RETURN,
    BANK_STATEMENTS,
    PROFIT_AND_LOSS_STATEMENT,
    BALANCE_SHEET,
    DEBT_SCHEDULE,
    PERSONAL_FINANCIAL_STATEMENT,
    BUSINESS_LICENSE,
    ARTICLES_OF_ORGANIZATION,
    DRIVER_LICENSE,
    PURCHASE_AGREEMENT,
    EQUIPMENT_INVOICE,
    INSURANCE_DOCUMENT,
    OTHER
}
