spring.application.name=platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/lending_db}
spring.datasource.username=${DB_USERNAME:lending_user}
spring.datasource.password=${DB_PASSWORD:lending_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}